name: android

on:
  workflow_call:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
  call-slack-succ:
    uses: ./.github/workflows/slack.yml
    needs: [build]
