name: inhouse deploy

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server'
        default: cbt
        type: choice
        options:
        - cbt
        - dev
        - qa
        - stg
      version:
        description: 'Version'
        required: true
        type: string
      bundleName:
        description: 'Bundle Name'
        required: true
        type: string
    
jobs:
  android:
    permissions:
      contents: read
      actions: read
    # needs: [build_test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout project repository
        uses: actions/checkout@v3

