name: start

on:
  workflow_dispatch:
    
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project repository
        uses: actions/checkout@v3
        
      # - name: Create/Update the tag
      #   uses: julbme/gh-action-manage-tag@v1
      #   with:
      #     name: v123
      #     state: present
      #     from: ${{ github.ref }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

      - name: runid
        run: |
          num=${{github.run_id}}
          num1=200
          a=$(($num*1000+$num1))
          echo a

  call-ios-succ:
    needs: [start]
    uses: ./.github/workflows/ios.yml

  call-android-succ:
    needs: [start]
    uses: ./.github/workflows/android.yml




