name: 안드로이드 배포

on:
  workflow_dispatch:

jobs:
  android: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout project repository
        uses: actions/checkout@v3
        
      - name: ${{github.actor}} uesr name
        run: ls
