name: iOS starter workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: slack noti
        uses: ./.github/workflows/main3.yml
        with:
          message: build end
