# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server'
        default: cbt
        type: choice
        options:
          - cbt
          - dev
          - qa
      version:
        description: 'Version'
        required: true
        type: string
      bundleName:
        description: 'Bundle Name'
        required: true
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-slack-noti:
    needs: [build]
    uses: ./.github/workflows/main3.yml
    with:
      data: '{"blocks":[{"type":"context","elements":[{"type":"mrkdwn","text":"App build started ::  [${{ inputs.server }}] ${{ inputs.version }}+${{ inputs.bundleName }}"}]}]}'
    secrets: inherit
    
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
