# This is a basic workflow to help you get started with Actions
name: CI
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server'
        default: cbt
        type: choice
        options:
          - cbt
          - dev
          - qa
      version:
        description: 'Version'
        required: true
        type: string
      bundleName:
        description: 'Bundle Name'
        required: true
        type: string

jobs:
  # call-slack-noti:
  #   needs: [build]
  #   uses: ./.github/workflows/main3.yml
  #   with:
  #     data: '{"attachments":[{"color":"#36a64f","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"iOS app has been deployed."}},{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"[${{ inputs.server }}] ${{inputs.version}}+${{ inputs.bundleName}}"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Testflight"},"url":"https://appstoreconnect.apple.com/apps/1643675480/testflight/ios","action_id":"button-action"}}]}]}'
  #   secrets:  
  #     WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #   # secrets: inherit
    
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: start noti
      #   uses: ./.github/workflows/main3.yml
      #   with:
      #     data: '{"attachments":[{"color":"#36a64f","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"iOS build started"}},{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"[${{ inputs.server }}] ${{inputs.version}}+${{ inputs.bundleName}}"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Testflight"},"url":"https://appstoreconnect.apple.com/apps/1643675480/testflight/ios","action_id":"button-action"}}]}]}'
      #   secrets:  
      #     WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze

      - name: Failing step
        id: demo
        run: exit 1

  call-slack-noti:
      uses: ./.github/workflows/main3.yml
      needs: [build]
      - if: ${{ needs.steps.demo.conclusion == 'failure'}}
        with:
          data: '{"attachments":[{"color":"#36a64f","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"build failed."}},{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"[${{ inputs.server }}] ${{inputs.version}}+${{ inputs.bundleName}}"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Testflight"},"url":"https://appstoreconnect.apple.com/apps/1643675480/testflight/ios","action_id":"button-action"}}]}]}'
        secrets:  
          WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # secrets: inherit      
      - if: ${{ needs.steps.demo.conclusion == 'success'}}
        with:
          data: '{"attachments":[{"color":"#36a64f","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"build success."}},{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"[${{ inputs.server }}] ${{inputs.version}}+${{ inputs.bundleName}}"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Testflight"},"url":"https://appstoreconnect.apple.com/apps/1643675480/testflight/ios","action_id":"button-action"}}]}]}'
        secrets:  
          WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # secrets: inherit