# This is a basic workflow to help you get started with Actions
name: CI
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server'
        default: cbt
        type: choice
        options:
          - cbt
          - dev
          - qa
      version:
        description: 'Version'
        required: true
        type: string
      bundleName:
        description: 'Bundle Name'
        required: true
        type: string

jobs:
  slack-noti-start:
    uses: ./.github/workflows/main3.yml
    with:
      data: '{"attachments":[{"color":"#36a64f","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"iOS app build started."}},{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"[${{ inputs.server }}] ${{inputs.version}}+${{ inputs.bundleName}}"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Testflight"},"url":"https://appstoreconnect.apple.com/apps/1643675480/testflight/ios","action_id":"button-action"}}]}]}'
    secrets:  
      WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
  build:
    needs: [slack-noti-start]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze

      - name: Failing step
        id: demo
        run: exit 1
        # if: ${{ failure() }}

      # - name: success
      #   if: ${{ success() }}

  slack-noti-fail:
      uses: ./.github/workflows/main3.yml
      needs: [build]
      if: ${{ failure()}}
      with:
        data: '{"attachments":[{"color":"#36a64f","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"build failed."}},{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"[${{ inputs.server }}] ${{inputs.version}}+${{ inputs.bundleName}}"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Testflight"},"url":"https://appstoreconnect.apple.com/apps/1643675480/testflight/ios","action_id":"button-action"}}]}]}'
      secrets:  
        WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  call-slack-succ:
      uses: ./.github/workflows/main3.yml
      needs: [build]
      if: ${{ success() }}
      with:
        data: '{"attachments":[{"color":"#36a64f","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"build success."}},{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"[${{ inputs.server }}] ${{inputs.version}}+${{ inputs.bundleName}}"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Testflight"},"url":"https://appstoreconnect.apple.com/apps/1643675480/testflight/ios","action_id":"button-action"}}]}]}'
      secrets:  
        WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      # secrets: inherit      
      # if: ${{ needs.steps.demo.conclusion == 'success'}}
      # with:
      #   data: '{"attachments":[{"color":"#36a64f","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"build success."}},{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"[${{ inputs.server }}] ${{inputs.version}}+${{ inputs.bundleName}}"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Testflight"},"url":"https://appstoreconnect.apple.com/apps/1643675480/testflight/ios","action_id":"button-action"}}]}]}'
      # secrets:  
      #   WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   # secrets: inherit