# This is a basic workflow to help you get started with Actions
name: CI
on:
  workflow_call:
    inputs:
      server:
        default: cbt
        type: string
      version:
        required: true
        type: string
      bundleName:
        required: true
        type: string
      deploy:
        default: build
        type: string
  workflow_dispatch:
    inputs:
      server:
        description: 'Server'
        default: cbt
        type: choice
        options:
          - cbt
          - dev
          - qa
      version:
        description: 'Version'
        required: true
        type: string
      bundleName:
        description: 'Bundle Name'
        required: true
        type: string
      deploy:
        description: 'only build? or deploy'
        default: build
        type: choice
        options:
          - build
          - deploy

jobs:
  slack-noti-start:
    uses: ./.github/workflows/slack.yml
    with:
      message: 'android build started :: [${{ inputs.server}}] ${{inputs.version}}+${{inputs.bundleName}}'
      color: '#36a64f'
    secrets:  
      WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
  build:
    needs: [slack-noti-start]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze

      - name: Failing step
        id: demo
        if: ${{ inputs.deploy == deploy }}
        run: exit 1

      # - name: success
      #   if: ${{ success() }}

  slack-noti-fail:
    uses: ./.github/workflows/slack.yml
    needs: [build]
    if: ${{ failure()}}
    with:
      message: '[${{ inputs.server}}] ${{inputs.version}}+${{inputs.bundleName}} build failure'
      color: '#C62D3C'
    secrets:  
      WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    

  call-slack-succ:
    uses: ./.github/workflows/slack.yml
    needs: [build]
    if: ${{ success() }}
    with:
      message: "[${{ inputs.server}}] ${{inputs.version}}+${{inputs.bundleName}} deploy success "
      store: "PlayStore Console"
      color: "#36a64f"
    secrets:  
      WEB_HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      STORE_LINK: ${{ secrets.STORE_LINK_AOS }}