name: ios run 테스트 

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: checkout project repository
        uses: actions/checkout@v3
        
      - name:  ${{github.actor}} user...
        run: |
          chmod +x ./.github/scripts/change_server_ios.sh
      - name: Create/Update the tag
        uses: julbme/gh-action-manage-tag@v1
        with:
          name: v123 123
          state: present
          from: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          
