# This is a basic workflow to help you get started with Actions
name: call main
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server'
        default: cbt
        type: choice
        options:
          - cbt
          - dev
          - qa
      version:
        description: 'Version'
        required: true
        type: string
      bundleName:
        description: 'Bundle Name'
        required: true
        type: string

jobs:
  call-main:
  - uses: ./.github/workflows/main.yml
    with:
      server: ${{ inputs.server }}
      version: ${{ inputs.version }}
      bundleName: ${{ inputs.bundleName }}