# This is a basic workflow to help you get started with Actions

name: macos slack notification

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos_slack_noti:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Slack Notify
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":${{ inputs.message }}}' ${{ secrets.SLACK_WEBHOOK_URL }}
